export const DOMAIN = 'https://casestudy.cyberlearn.vn/'
export const TOKEN = 'access_token'
export const USER_LOGIN = 'USER_LOGIN'

export const ADD_HISTORY = 'ADD_HISTORY'

export const STATUS_CODE = {
    SUCCESS: 200,
    NOT_FOUND: 404,
    SERVER_ERROR: 500
}


// ----------- Others constants -----------
export const DISPLAY_LOADING = 'DISPLAY_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'

export const OPEN_DRAWER_WITH_FORM_EDIT = 'OPEN_DRAWER_WITH_FORM_EDIT'
export const OPEN_DRAWER_WITH_FORM_EDIT_USER = 'OPEN_DRAWER_WITH_FORM_EDIT_USER'
export const OPEN_DRAWER_WITH_FORM_EDIT_PROJECT = 'OPEN_DRAWER_WITH_FORM_EDIT_PROJECT'

export const ADD_HANDLE_SUBMIT_FUNCTION = 'ADD_HANDLE_SUBMIT_FUNCTION'

// ----------- User constants -----------
export const USLOGIN = 'USLOGIN'
export const SHOW_USER_LOGIN_INFO = 'SHOW_USER_LOGIN_INFO'


export const SIGN_UP_SAGA = 'SIGN_UP_SAGA'
export const SIGN_IN_SAGA = 'SIGN_IN_SAGA'

export const GET_USER_SAGA = 'GET_USER_SAGA'
export const GET_USER = 'GET_USER'

export const GET_USER_WITH_KEYWORD = 'GET_USER_WITH_KEYWORD'
export const GET_USER_WITH_KEYWORD_WITHOUT_LOADING = 'GET_USER_WITH_KEYWORD_WITHOUT_LOADING'
export const GET_USER_FOR_AUTOCOMPLETE = 'GET_USER_FOR_AUTOCOMPLETE'

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA'

export const EDIT_USER_SAGA = 'EDIT_USER_SAGA'

export const ASSIGN_USER_TO_PROJECT = 'ASSIGN_USER_TO_PROJECT'
export const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT'




// ----------- Project constants -----------
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const GET_PROJECT_WITH_KEYWORD = 'GET_PROJECT_WITH_KEYWORD'

export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA'
export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY'

export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'

export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'

export const EDIT_PROJECT_SAGA = 'EDIT_PROJECT_SAGA'

export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA'
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'

export const OPEN_DRAWER_WITH_FORM_CREATE_TASK = 'OPEN_DRAWER_WITH_FORM_CREATE_TASK'

export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA'
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE'

export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA'
export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY'

export const GET_ALL_PROJECT_CHO_DROPDOWN_SAGA = 'GET_ALL_PROJECT_CHO_DROPDOWN_SAGA'
export const GET_ALL_PROJECT_CHO_DROPDOWN = 'GET_ALL_PROJECT_CHO_DROPDOWN'

export const GET_ALL_USER_CHO_DROPDOWN_SAGA = 'GET_ALL_USER_CHO_DROPDOWN_SAGA'
export const GET_ALL_USER_CHO_DROPDOWN = 'GET_ALL_USER_CHO_DROPDOWN'

export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA'

export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA'
export const GET_ALL_STATUS = 'GET_ALL_STATUS'

export const GET_PROJECT_DETAIL_FOR_CREATE_TASK_SAGA = 'GET_PROJECT_DETAIL_FOR_CREATE_TASK_SAGA'
export const GET_PROJECT_DETAIL_FOR_CREATE_TASK = 'GET_PROJECT_DETAIL_FOR_CREATE_TASK'

export const DELETE_TASK_SAGA = 'DELETE_TASK_SAGA'


// ----------- Task constants -----------
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA'
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL'

export const UPDATE_TASK_MODAL = 'UPDATE_TASK_MODAL'

export const UPDATE_ASSIGNEE_IN_TASK_MODAL = 'UPDATE_ASSIGNEE_IN_TASK_MODAL'
export const REMOVE_ASSIGNEE_IN_TASK_MODAL = 'REMOVE_ASSIGNEE_IN_TASK_MODAL'

export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA'
export const UPDATE_TASK = 'UPDATE_TASK'

export const HANDLE_SERIES_CHANGE_MODAL_VA_POST_API_SAGA = 'HANDLE_SERIES_CHANGE_MODAL_VA_POST_API_SAGA'


// ----------- Comment constants -----------
export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA'
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA'
export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA'

export const GHI_NHO_COMMENT_ID_KHI_NHAP_EDIT_COMMENT = 'GHI_NHO_COMMENT_ID_KHI_NHAP_EDIT_COMMENT'